# Generated by Django 6.1 on 2026-08-28 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_organization_alter_user_role_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_emp_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('org_emp_code', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('band', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(max_length=100)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('father_husband_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('doj', models.DateField(help_text='Date of Joining')),
                ('dos', models.DateField(blank=True, help_text='Date of Separation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='authentication.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('house_rent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utilities_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='authentication.employeeprofile')),
            ],
        ),
    ]
