# Generated by Django 6.1 on 2026-09-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employeeprofile_salarystructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.DeleteModel(
            name='SalaryStructure',
        ),
    ]
