# Generated by Django 6.1 on 2026-09-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_options_delete_salarystructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
